### PR TITLE
[FTPSERVER-506] Binary compatibility is broken in ftpserver-core 1.1.3,

### PR DESCRIPTION
**Pull request by garydgregory**
1.2.0 vs 1.1.2

### CODE REVIEW

**Comment by elecharny** [comment]
Hi Gary,

I'm nor sure this is a needed change. The implementation already returns an array containing "TLSv1.2":

```
public class DefaultSslConfiguration implements SslConfiguration {
...
    private String[] enabledProtocols = new String[] {"TLSv1.2"};
...
    /**
     * @see SslConfiguration#getEnabledProtocols()
     */
    public String[] getEnabledProtocols() {
        return enabledProtocols;
    }

```

**Comment by garydgregory** [comment]
Hello @elecharny ,
The code you quote is completely irrelevant. What matters is that a public interface breaks binary compatibility. Since user can implement the public interface, those implementations no longer complie! The fix is simple and provides both binary and source compatibility.

**Comment by garydgregory** [comment]
> Hi @garydgregor,
> 
> sure enough, but I reversed the {{SslConfiguration}} interface to what it was in 1.1.2, so I can't seer how 1.1.4v breaks ther binary compatibility.
> 
> Sorry if that sounds dumb, I'm a bit overloaded atm...

Hi @elecharny 
1.1.4 is ok 1.2.0 is broken, please see my explanation in Jira.

**Comment by garydgregory** [comment]
Closing: Done in git master and more.

**Pull request closed without merging**
